export const FAMILY_SIZE_MAPPING: any = {
  one: 1,
  two: 2,
  three: 3,
  four: 4,
  five: 5,
  six: 6,
  seven: 7,
  eight: 8,
  nine: 9,
  ten: 10,
};

// Caste mapping dictionary
export const CASTE_MAPPING: any = {
  chhetriPahad: "क्षेत्री (पहाड)",
  tharu: "थारु",
  rai: "राई",
  brahminPahad: "ब्राह्मण (पहाड)",
  tamang: "तामाङ्ग",
  limbu: "लिम्बु",
  dhimal: "धिमाल",
  bishwakarma: "विश्वकर्मा (कामी, सुनार, ओड, चुनँरा, पार्की, टमटा)",
  newar: "नेवार",
  tajpuriya: "ताजपुरिया",
  gurung: "गुरुङ्ग",
  magar: "मगर",
  brahminTerai: "ब्राम्हण (तराई)",
  pariyar: "परियार (दमाई, दर्जी, सुचिकार, नगर्ची, ढोली, हुडरके)",
  chaudhary: "चौधरी",
  sanyasiDashnami: "सन्यासी/दशनामी",
  sarki: "सार्की (मिजार, चर्मकार, भूल)",
  majhi: "माझी",
  musahar: "मुसहर",
  bhujel: "भूजेल",
  teli: "तेली",
  bantar: "बाँतर",
  kisan: "किसान",
  meche: "मेचे (बोडो)",
  yadav: "यादव",
  sherpa: "शेर्पा",
  muslim: "मुस्लिम",
  danuwar: "दनुवार",
  koiri: "कोइरी",
  haluwai: "हलुवाई",
  hajamThakur: "हजाम/ठाकुर",
  bengali: "बंगाली",
  khawas: "खवास",
  gandharva: "गन्धर्व (गाईने)",
  chamar: "चमार (राम, मोची, हरिजन, रविदास)",
  kumal: "कुमाल",
  thakuri: "ठकुरी",
  yakha: "याख्खा",
  sunuwar: "सुनुवार",
  khatwe: "खत्वे (मण्डल, खड्ग)",
  kalwar: "कलवार",
  kalar: "कलर",
  mahato: "महतो",
  amat: "अमात",
  dom: "डोम (मरिक)",
  vadi: "वादी",
  kakahiya: "ककैहिया",
  baniya: "बानिया",
  dusadh: "दुसाध (पासवान, हजरा)",
  marwadi: "मारवाडी",
  badhai: "बढही",
  rajput: "राजपुत",
  jogi: "जोगि",
  sudhi: "सुढी",
  sonar: "सोनार",
  rajdhov: "राजधोव",
  kori: "कोरी",
  mallah: "मल्लाह",
  fri: "फ्रि",
  pasi: "पासी",
  bidh: "विड/बिण्डा",
  khatik: "खटिक",
  lohar: "लोहार",
  tatma: "तत्मा (ताँती, दास)",
  raute: "राउटे",
  mugali: "मुगाली",
  vyasi: "व्याँसी",
  bhote: "भोटे",
  churoute: "चुरौटे",
  kurmi: "कुर्मी",
  meheta: "मेहेता",
  jain: "जैन",
  chidimar: "चिडिमार",
  vankariya: "वनकरिया",
  kumhar: "कुम्हार",
  barhaGaunleThakali: "बार्‍हगाउँले थकाली",
  thami: "थामी",
  topkegela: "तोप्केगेला",
  jirel: "जिरेल",
  kushwaha: "कुश्वाहा",
  lhopha: "ल्होपा",
  lodh: "लोध",
  lepcha: "लेप्चा",
  larke: "लार्के",
  rajbhar: "राजभर",
  mali: "माली",
  baramo: "बारामो",
  nurang: "नुराङ",
  thudam: "थुदाम",
  kushbadiya: "कुशबडिया",
  kayastha: "कायस्थ",
};

export const LANGUAGE_MAPPING: any = {
  nepali: "नेपाली",
  tharu: "थारु",
  rai: "राई",
  rajbanshi: "राजवंशी",
  dhimal: "धिमाल",
  tamang: "तामाङ",
  maithili: "मैथिली",
  limbu: "लिम्बु",
  magar: "मगर",
  gurung: "गुरुङ",
  majhi: "माझी",
  bantawa: "बान्तवा",
  chamling: "चाम्लिङ",
  others: "अन्य",
  bhojpuri: "भोजपुरी",
  kulung: "कुलुङ",
  lohorung: "लोहोरुङ",
  sherpa: "शेर्पा",
  santhali: "सन्थाली",
  nachiring: "नाछिरिङ",
  bajjika: "बज्जिका",
  urdu: "उर्दू",
  nepal: "नेपाल",
  unspecifiedLanguage: "भाषा उल्लेख नभएको",
  mewahang: "मेवाहाङ",
  bengali: "बङ्गाली",
  dumi: "डुमी",
  thulung: "थुलुङ",
  sangpang: "साङ्पाङ",
  yakha: "याक्खा",
  hindi: "हिन्दी",
  bhujel: "भुजेल",
  khaling: "खालिङ",
  danuwar: "दनुवार",
  awadhi: "अवधि",
  doteli: "डोटेली",
  urau: "उराउ",
  sunuwar: "सुनुवार",
  yamphu: "याम्फु",
  pahari: "पहरी",
  sonaha: "सोनाहा",
  wambule: "वाम्बुले",
  nagamese: "नागामिज",
  tajpuriya: "ताजपुरिया",
  achhami: "अछामी",
  baitadeli: "बैतडेली",
  dailekhi: "दैलेखी",
  jirel: "जिरेल",
  angika: "अंगिका",
};

export const GENDER_MAPPING: any = {
  male: "पुरुष",
  female: "महिला",
  other: "अन्य",
};

export const MARITAL_STATUS_MAPPING: any = {
  married: "विवाहित",
  unmarried: "अविवाहित",
  widowOrWidower: "एकल महिला/पुरुष",
  separated: "छुट्टिएको",
  divorced: "पारपाचुके/सम्वन्ध विच्छेद",
  others: "अन्य",
  split: "अलग भए",
};

export const OCCUPATION_MAPPING: any = {
  student: "विद्यार्थी",
  housewife: "गृहणी",
  dailyWageWorker: "ज्याला/मजदुरी",
  industryTradeAgriculture: "उद्योग, व्यापार, कृषि",
  foreignEmployment: "वैदेशिक रोजगारी",
  otherSelfEmployment: "अन्य स्वरोजगार",
  otherEmployment: "अन्य रोजगारी",
  otherUnemployment: "अन्य बेरोजगार",
  business: "व्यापार",
  ngoJob: "गैरसरकारी नोकरी/जागिर",
  governmentJob: "सरकारी नोकरी/जागिर",
  animalHusbandry: "पशुपालन",
};

export const RELIGION_MAPPING: any = {
  islam: "इस्लाम",
  kirat: "किराँत",
  christian: "कृश्चियन",
  jain: "जैन",
  prakriti: "प्रकृति",
  bahai: "बहाई",
  bon: "बोन",
  buddhist: "बौद्ध",
  sikh: "सिख",
  hindu: "हिन्दु",
  others: "अन्य",
};

export const DISABILITY_MAPPING: any = {
  autism: "अटिजम्",
  lowVision: "न्यून दृष्टियुक्त",
  completeBlindness: "पूर्ण दृष्टिविहिन",
  deafness: "बहिरापन",
  multipleDisabilities: "बहुअपाङ्गता",
  intellectualDisability: "बौद्धिक अपाङ्गता",
  mentalOrPsychosocialDisability: "मानसिक वा मनोसामाजिक",
  physicalDisability: "शारिरिक अपाङ्गता",
  deafblindness: "श्रवण दृष्टिविहिन",
  hardOfHearing: "सुस्तश्रवण",
  speechAndLanguageImpairment: "स्वर र बोलाई",
  others: "अन्य",
};

export const BLOOD_GROUP_MAPPING: any = {
  oPositive: "ओ पोजेटिभ",
  aPositive: "ए पोजिटिभ",
  oNegative: "ओ नेगेटिभ",
  bPositive: "बि पोजेटिभ",
  abPositive: "एबि पोजिटिभ",
  aNegative: "ए नेगेटिभ",
  bNegative: "बि नेगेटिभ",
  abNegative: "एबि नेगेटिभ",
};

export const HEALTH_STATUS_MAPPING: any = {
  healthy: "स्वस्थ",
  minorIllness: "सामान्य रोगी",
  chronicIllness: "दीर्घ रोगी",
};

export const DISEASE_MAPPING: any = {
  arthritis: "बाथ",
  diabetes: "मधुमेह (डायबिटिज)",
  asthmaOrRespiratoryDisease: "दम/श्वासप्रश्वास सम्बन्धी",
  kidneyOrLiverDisease: "मृगौला/कलेजोको रोग",
  ulcerOrIntestinalDisease: "अल्सर/आन्द्राको रोग",
  cancer: "अर्बुद (क्यान्सर)",
  heartDisease: "मुटु रोग",
  highBloodPressure: "उच्च रक्तचाप",
  lowBloodPressure: "निम्न रक्तचाप",
  gynecologicalDisease: "स्त्रीरोग",
  epilepsy: "इपिलेप्सी",
  alzheimer: "अल्जाईमर्स",
  parkinsons: "पार्किन्सन्स्",
  others: "अन्य",
};

export const LITERACY_RATE_MAPPING: any = {
  illiterate: "0",
  literate: "1",
};

export const EDUCATION_LEVEL_MAPPING: any = {
  primary: "Primary", // Mapping "Primary"
  secondary: "Secondary", // Mapping "Secondary"
  higherSecondary: "Higher Secondary", // Mapping "Higher Secondary"
  bachelorsOrEquivalent: "Bachelor", // Mapping "Bachelor"
  mastersOrEquivalent: "Master", // Mapping "Master"
  phd: "PhD", // Mapping "PhD"
  others: "अन्य",
};

export const SCHOOL_DROPOUT_MAPPING: any = {
  notDroppedOut: false,
  droppedOut: true,
};

export const DROPOUT_REASON_MAPPING: any = {
  lackOfInterest: "पढ्ने इच्छा नभएर",
  lackOfFunds: "पढ्ने खर्च नभएर",
  movingToAnotherLocation: "बसाई सरेकोले",
  marriage: "विवाह भएर",
  schoolTooFar: "शैक्षिक संस्था टाढा भएर",
  others: "अन्य",
  familyIssues: "पारिवारिक समस्या",
  healthProblems: "स्वास्थ्य समस्याहरू",
  jobOpportunities: "रोजगार अवसरहरू",
  schoolEnvironment: "विद्यालयको वातावरण",
};

export const EDUCATION_DIVISION_MAPPING: any = {
  first: "प्रथम",
  second: "द्वितीय",
  third: "तृतीय",
  unspecified: "श्रेणी नखुलेकाे",
};

export const FOREIGN_EMPLOYMENT_MAPPING: any = {
  no: "स्वदेशमा अन्यत्र",
  yes: "विदेशमा",
};

export const FOREIGN_WORK_MAPPING: any = {
  qatar: "कतार",
  dubai: "दुवैई",
  saudiArabia: "साउदी अरेबिया",
  malaysia: "मलेशिया",
  india: "भारत",
  kuwait: "कुवेत",
  japan: "जापान",
  bahrain: "बहराईन",
  australia: "अष्ट्रेलिया",
  hongKong: "हङकङ",
  romania: "रोमानिया",
  southKorea: "दक्षिण कोरिया",
  portugal: "पोर्चुगल",
  northKorea: "उत्तर कोरिया",
  uk: "संयुक्त अधिराज्य बेलायत",
  singapore: "सिंगापुर",
  maldives: "माल्दिभ्स",
  peru: "पेरु",
  cyprus: "साईप्रस",
  austria: "अष्‍ट्रिया",
  malta: "माल्टा",
  canada: "क्यानडा",
  usa: "संयुक्त राज्य अमेरिका",
  brunei: "ब्रुनाई",
  norway: "नर्वे",
  un: "संयुक्त राष्ट्र संघ",
  poland: "पोल्याण्ड",
  southAfrica: "दक्षिण अफ्रिका",
  denmark: "डेनमार्क",
  russia: "रसिया",
  macau: "मकाउ",
  niger: "नाइजर",
  tokyo: "टोक्यो",
  croatia: "क्रोएसिया",
  israel: "ईजरायल",
  yemen: "यमन",
  mongolia: "मंगोलिया",
  netherlands: "नेदरल्याण्ड",
  germany: "जर्मनी",
  azerbaijan: "अजरबैजान",
  bosnia: "बोस्निया",
  france: "फ्रान्स",
  newZealand: "न्यूजिल्याण्ड",
  nigeria: "नाइजेरिया",
  italy: "ईटाली",
  armenia: "अर्मेनिया",
  somalia: "सोमालिया",
  uae: "संयुक्त अरब ईमिरेट्स",
  ukraine: "युक्रेन",
  myanmar: "म्यानमार",
  mexico: "मेक्सिको",
  vaticanCity: "भ्याटिकन सिटी",
  bangladesh: "बंगलादेश",
  pakistan: "पाकिस्तान",
  westernSamoa: "पश्‍चिमी समोआ",
  nepal: "नेपाल",
  taiwan: "ताइवान",
  togo: "टोगो",
  zaire: "जायर",
  china: "चीन",
  chile: "चिली",
  greece: "ग्रीस",
  kosovo: "कोसोभो",
  kathmandu: "काठमाण्डौ",
  congo: "कंगो",
  iraq: "इराक",
  argentina: "अर्जेन्टिना",
  aruba: "अरुबा",
};

export const VEGETABLE_MAPPING: any = {
  potato: "आलु",
  bitterGourdAndGourd: "करेला, घिरौला, चिचिण्डो",
  cucumberAndPumpkin: "काँक्रो, लौका, फर्सी",
  tomato: "गोलभेंडा",
  pointedGourdAndCucumber: "परबल, कुन्द्रुक, काँक्रो",
  cabbageCauliflowerMustard: "बन्दा/काउली/रायो",
  bean: "बोडी",
  others: "अन्य",
};

export const CEREAL_MAPPING: any = {
  millet: "कोदो",
  wheat: "गहुँ",
  rice: "धान",
  maize: "मकै",
  others: "अन्य",
};

export const PULSE_MAPPING: any = {
  chickpea: "चना",
  lentil: "दाल",
  soybean: "भटमास",
  mungBean: "मुसरो",
  pigeonPea: "रहर",
  bean: "सिमी",
  others: "अन्य",
};

export const OILSEED_MAPPING: any = {
  flaxOrSesame: "आलस/तिल",
  mustard: "तोरी/सस्र्यु",
  sunflower: "सूर्यमुखी",
  others: "अन्य",
};

export const FRUIT_MAPPING: any = {
  mango: "आँप",
  peach: "आरुवखडा",
  lemon: "कागती",
  kiwi: "किवी",
  banana: "केरा",
  dragonFruit: "ड्रागन फ्रुट",
  guava: "मेवा",
  lychee: "लिची",
  orange: "सुन्तला",
  strawberry: "स्ट्रवेरी",
  apple: "स्याउ",
  others: "अन्य",
};

export const CASH_CROP_MAPPING: any = {
  gingerOrTurmeric: "अदुवा/वेसार",
  sugarcane: "ऊखु",
  mushroom: "च्याउ",
  jute: "जुट",
  onionOrGarlic: "प्याज/लसुन",
  others: "अन्य",
};

export const DRINKING_WATER_MAPPING: any = {
  tubewellOrHandpump: "ट्युववेल/हेन्डपम्प",
  springWater: "मूलको पानी",
  pipedWaterInsideCompound: "पाइपधारा घर कम्पाउण्डमा",
  other: "अन्य",
  pipedWaterOutsideCompound: "पाइपधारा घर कम्पाउण्ड बाहिर",
  deepBoring: "डिप वोरिङ्ग",
  jarOrBottledWater: "जार/बोतल",
  coveredWell: "ढाकिएको इनार/कुवा",
  riverOrStream: "नदी खोला",
  uncoveredWell: "नढाकिएको इनार/कुवा",
};

export const TOILET_MAPPING: any = {
  basicToilet: "साधारण चर्पी",
  flushWithSepticTank: "फ्लस भएको (सेप्टिक ट्याङ्क)",
  temporaryToilet: "कच्ची चर्पी",
  noToilet: "शौचालय नभएको",
  flushWithPublicSewer: "फ्लस भएको (सार्वजनिक ढल)",
  communityOrPublicToilet: "सामुदायिक/सार्वजनिक चर्पी",
};

export const FAMILY_DEATH_MAPPING: any = {
  familyDeath: true,
};
