export const databaseSchema = {
  base_entity: {
    createdAt: "timestamp",
    updatedAt: "timestamp",
    modifiedBy: "numeric",
  },
  option: {
    value: "text",
    order_number: "integer",
    question: "Relation[() => question_1.question]",
  },
  survey: {
    name: "text",
    code: "text",
    description: "text",
    is_active: "boolean",
    categories: "Relation[() => category_1.category]",
    responses: "Relation[() => response_1.response]",
  },
  category: {
    name: "text",
    allow_multiple_response: "boolean",
    order_number: "integer",
    questions: "Relation[() => question_1.question]",
    surveys: "Relation[() => survey_1.survey]",
  },
  question: {
    type: "enum",
    is_required: "boolean",
    description: "text",
    order_number: "integer",
    options: "Relation[() => option_1.option]",
    categories: "Relation[() => category_1.category]",
    answers: "Relation[() => answer_1.answer]",
  },
  answer: {
    answer: "text",
    group_id: "text",
    question: "Relation[() => question_1.question]",
    response: "Relation[() => response_1.response]",
  },
  response: {
    google_plus_code: "text",
    survey_taken_place_latitude: "decimal",
    survey_taken_place_longitude: "decimal",
    survey: "Relation[() => survey_1.survey]",
    survey_taken_by: "Relation[() => user_1.user]",
    answers: "Relation[() => answer_1.answer]",
  },
  sifarish: {
    ownerEng: "varchar",
    ownerNepali: "varchar",
    municipality: "varchar",
    tole: "varchar",
    uuid: "varchar",
    isValid: "boolean",
    cadastral: "Relation[() => cadastral_1.cadastral]",
  },
  valuation_sifarish: {
    ownerEng: "varchar",
    ownerNepali: "varchar",
    municipality: "varchar",
    tole: "varchar",
    uuid: "varchar",
    isValid: "boolean",
    cadastral: "Relation[() => cadastral_1.cadastral]",
  },
  cadastral: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    parcel_no: "numeric",
    ward_no: "character varying",
    shape_area: "double precision",
    sheet_no: "character varying",
    zone: "character varying",
    zone_nepali: "character varying",
    former_vdc: "character varying",
    remarks: "character varying",
    valuation: "real",
    cadastral_update_requests:
      "Relation[() => cadastral_update_request_1.cadastral_update_request]",
    sifarish: "Relation[() => sifarish_1.sifarish]",
    valuation_sifarish:
      "Relation[() => valuation_sifarish_1.valuation_sifarish]",
  },
  cadastral_update_request: {
    id: "integer",
    parcel_no: "numeric",
    ward_no: "character varying",
    sheet_no: "character varying",
    zone: "character varying",
    zone_nepali: "character varying",
    former_vdc: "character varying",
    remarks: "character varying",
    user_comment: "character varying",
    valuation: "real",
    status: "enum",
    user: "Relation[() => user_1.user]",
    cadastral: "Relation[() => cadastral_1.cadastral]",
  },
  user: {
    email: "varchar",
    password: "varchar",
    role: "enum",
    firstName: "varchar",
    lastName: "varchar",
    phone: "varchar",
    address: "varchar",
    position: "varchar",
    blocked: "boolean",
    login_log: "Relation[() => login_log_1.login_log]",
    responses: "Relation[() => response_1.response]",
    cadastral_update_requests:
      "Relation[() => cadastral_update_request_1.cadastral_update_request]",
  },
  login_log: {
    loginTime: "timestamp",
    ipAddress: "varchar",
    userAgent: "varchar",
    accessToken: "varchar",
    refreshToken: "varchar",
    createdAt: "timestamp",
    accessTokenExpiresAt: "timestamp",
    refreshTokenExpiresAt: "timestamp",
    revoked: "boolean",
    user: "Relation[() => user_1.user]",
  },
  demo_request: {
    firstName: "varchar",
    lastName: "varchar",
    email: "varchar",
    phoneNumber: "varchar",
    organizationName: "varchar",
    reasonForDemo: "text",
    validTill: "timestamp",
    status: "enum",
    createdAt: "timestamp",
    updatedAt: "timestamp",
  },

  ward: {
    ogc_fid: "integer",
    geometry: "geometry",
    ward: "numeric",
    area_sqkm: "double precision",
    shape_area: "double precision",
  },
  cadastral_points: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    parcel_no: "numeric",
    ward_no: "character varying",
    shape_area: "double precision",
    sheet_no: "character varying",
    zone: "character varying",
    zone_nepali: "character varying",
    former_vdc: "character varying",
    remarks: "character varying",
    valuation: "real",
  },
  agriculture: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    shape_area: "double precision",
    zone: "character varying",
  },
  commercial: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    shape_area: "double precision",
    zone: "character varying",
  },
  forest: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    shape_area: "double precision",
    zone: "character varying",
  },
  industrial: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    shape_area: "double precision",
    zone: "character varying",
  },
  public_use: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    shape_area: "double precision",
    zone: "character varying",
  },
  residential: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    shape_area: "double precision",
    zone: "character varying",
  },
  water_bodies: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    shape_area: "double precision",
    zone: "character varying",
  },
  house: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    latitude: "double precision",
    longitude: "double precision",
    house_id: "double precision",
    owner: "character varying",
    tole: "character varying",
    road_code: "character varying",
    block: "character varying",
    x_starting: "double precision",
    y_starting: "double precision",
    distance_f: "double precision",
    rank_from: "numeric",
    house_code: "character varying",
    google_plu: "character varying",
    name_english: "character varying",
    name_nepali: "character varying",
    ward: "character varying",
    is_number_plate_installed: "boolean",
  },
  road_cordinate: {
    ogc_fid: "integer",
    recorded_on: "timestamp",
    pavement_type: "character varying",
    start_longitude: "double precision",
    start_latitude: "double precision",
    end_longitude: "double precision",
    end_latitude: "double precision",
    road: "Relation[() => road_1.road]",
  },
  road: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    id: "numeric",
    road_class: "character varying",
    name_english: "character varying",
    name_nepali: "character varying",
    pavement_type: "character varying",
    drain_type: "character varying",
    wards_touched: "character varying",
    length: "double precision",
    class: "character varying",
    reserve: "numeric",
    width_feet: "double precision",
    ward_touch: "character varying",
    houses_touched: "numeric",
    scoring_h: "double precision",
    priority_i: "numeric",
    scoring_p: "numeric",
    priority_1: "numeric",
    scoring_w: "double precision",
    priority_2: "numeric",
    weighted_a: "double precision",
    wighted_pr: "numeric",
    width_grou: "numeric",
    row: "double precision",
    row_ft: "double precision",
    row_calcul: "double precision",
    road_cordinates: "Relation[() => road_cordinate_1.road_cordinate]",
  },
  pole: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    id: "numeric",
    ward: "numeric",
  },
  digital_profile_agriculturecashcrop: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    cash_crop_production: "character varying",
    cash_crop_production_area: "character varying",
    sales_result: "real",
    ward_no: "character varying",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_agricultureflowers: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    flower_production: "character varying",
    flower_production_area: "character varying",
    sales_result: "real",
    ward_no: "character varying",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_agriculturefoodcrop: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    food_production: "character varying",
    food_production_area: "character varying",
    sales_result: "real",
    ward_no: "character varying",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_agriculturefruits: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    fruit_production: "character varying",
    fruit_production_area: "character varying",
    sales_result: "real",
    ward_no: "character varying",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_agricultureoilseeds: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    oilseed_production: "character varying",
    oilseed_production_area: "character varying",
    sales_result: "real",
    ward_no: "character varying",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_agriculturepulses: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    pulse_production: "character varying",
    pulse_production_area: "character varying",
    sales_result: "real",
    ward_no: "character varying",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_agriculturevegetable: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    veg_production: "character varying",
    veg_production_area: "character varying",
    sales_result: "real",
    ward_no: "character varying",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_buildingdetail: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    house_image: "character varying",
    house_image_url: "text",
    land_type: "character varying",
    type_of_house: "character varying",
    house_storeys: "numeric",
    house_area: "real",
    house_made_date: "character varying",
    has_house_map_passed: "character",
    has_all_requirements_fulfilled: "character",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_cookingfuel: {
    id: "integer",
    main_fuel: "character varying",
    other_fuel: "character varying",
    stove_type: "character varying",
    other_stove_type: "character varying",
    has_ventilation: "text",
    ventilation_type: "character varying",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_drinkingwatersurvey: {
    id: "integer",
    ward_no: "integer",
    main_source: "character varying",
    other_main_source: "character varying",
    purification_done: "boolean",
    purification_method: "character varying",
    other_purification_method: "character varying",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_education: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    is_literate: "boolean",
    education_degree: "character varying",
    has_ended_study_abruptly: "boolean",
    reason_to_end_study: "character varying",
    branch_of_study: "character varying",
    education_qualification_type: "character varying",
    division_of_study: "character varying",
    percentage: "real",
    gpa: "real",
    education_institution_name: "character varying",
    education_passed_year: "character varying",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_expense: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    expense_field: "text",
    expense_amount: "real",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_familydeath: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    death_person_name: "character varying",
    relationship: "character varying",
    gender: "character varying",
    age: "numeric",
    reason_of_death: "character varying",
    was_pregnant: "boolean",
    has_newborn: "boolean",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_citizenshipdetail: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    has_citizenship: "character",
    reason_not_have_citizenship: "character varying",
    citizenship_no: "character varying",
    date_issued: "character varying",
    district_of_issue: "character varying",
    image_of_citizenship_front: "character varying",
    citizenship_image_front_url: "text",
    image_of_citizenship_back: "text",
    citizenship_image_back_url: "text",
    person:
      "Relation[() => digital_profile_familymember_1.digital_profile_familymember]",
  },
  digital_profile_currentlivingstatus: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    living_status: "character varying",
    digital_profile_currentlivingstatuses: "character varying",
    reason_to_live_in_foreign: "character varying",
    province: "character varying",
    district: "character varying",
    palika: "character varying",
    ward_no_live_in_other_place_within_country: "integer",
    reason_to_live_in_other_place_within_country: "character varying",
    person:
      "Relation[() => digital_profile_familymember_1.digital_profile_familymember]",
  },
  digital_profile_disabilitystatus: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    has_disability: "boolean",
    status_of_disability: "character varying",
    has_disability_card: "boolean",
    type_of_disability_card: "character varying",
    disability_card_no: "character varying",
    person:
      "Relation[() => digital_profile_familymember_1.digital_profile_familymember]",
  },
  digital_profile_epidemicdetail: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    has_pandemic_infected: "boolean",
    pandemic_name: "character varying",
    date_of_infection: "text",
    symptoms_of_pandemic: "text",
    stay_after_contaminated: "text",
    has_need_of_oxygen: "text",
    days_to_discharge_from_hospital: "integer",
    has_covid19_vaccine_taken: "text",
    dose_of_vaccine: "character varying",
    covid19_vaccine_taken_name: "character varying",
    has_health_insurance: "boolean",
    has_account_bank_or_other_institution: "boolean",
    bank_or_other_institution_name: "character varying",
    is_veg: "boolean",
    person:
      "Relation[() => digital_profile_familymember_1.digital_profile_familymember]",
  },
  digital_profile_healthstatus: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    status_of_health: "character varying",
    disease_name: "character varying",
    person:
      "Relation[() => digital_profile_familymember_1.digital_profile_familymember]",
  },
  digital_profile_nationalidentity: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    has_national_registration_card: "boolean",
    national_registration_card_no: "character varying",
    issued_date: "character varying",
    person:
      "Relation[() => digital_profile_familymember_1.digital_profile_familymember]",
  },
  digital_profile_pandetail: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    has_pan: "boolean",
    pan_no: "character varying",
    person:
      "Relation[() => digital_profile_familymember_1.digital_profile_familymember]",
  },
  digital_profile_passportdetail: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    has_passport: "boolean",
    passport_no: "character varying",
    place_of_issue: "character varying",
    date_of_issue: "date",
    expiry_date: "date",
    person:
      "Relation[() => digital_profile_familymember_1.digital_profile_familymember]",
  },
  digital_profile_socialsecurity: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    has_social_security_card: "boolean",
    social_security_no: "character varying",
    person:
      "Relation[() => digital_profile_familymember_1.digital_profile_familymember]",
  },
  digital_profile_voterdetail: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    has_voter_card: "boolean",
    voter_card_no: "character varying",
    voting_place: "character varying",
    person:
      "Relation[() => digital_profile_familymember_1.digital_profile_familymember]",
  },
  digital_profile_familymember: {
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    first_name: "text",
    last_name: "text",
    full_name_nepali: "text",
    full_name_eng: "text",
    gender: "text",
    relation_with_family_head: "text",
    dob: "text",
    age: "numeric",
    email: "text",
    mobile_no: "text",
    blood_group: "text",
    caste: "text",
    religion: "text",
    language: "text",
    occupation: "text",
    marital_status: "text",
    skill: "text",
    interest_areas: "text",
    digital_profile_citizenshipdetails:
      "Relation[() => digital_profile_citizenshipdetail_1.digital_profile_citizenshipdetail]",
    digital_profile_currentlivingstatuses:
      "Relation[() => digital_profile_currentlivingstatus_1.digital_profile_currentlivingstatus]",
    digital_profile_disabilitystatuses:
      "Relation[() => digital_profile_disabilitystatus_1.digital_profile_disabilitystatus]",
    digital_profile_epidemicdetails:
      "Relation[() => digital_profile_epidemicdetail_1.digital_profile_epidemicdetail]",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
    digital_profile_healthstatuses:
      "Relation[() => digital_profile_healthstatus_1.digital_profile_healthstatus]",
    digital_profile_nationalidentities:
      "Relation[() => digital_profile_nationalidentity_1.digital_profile_nationalidentity]",
    digital_profile_pandetails:
      "Relation[() => digital_profile_pandetail_1.digital_profile_pandetail]",
    digital_profile_passportdetails:
      "Relation[() => digital_profile_passportdetail_1.digital_profile_passportdetail]",
    digital_profile_socialsecurities:
      "Relation[() => digital_profile_socialsecurity_1.digital_profile_socialsecurity]",
    digital_profile_voterdetails:
      "Relation[() => digital_profile_voterdetail_1.digital_profile_voterdetail]",
  },
  digital_profile_healthtreatment: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    treatment_place: "text",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_land: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    land_record_image: "text",
    land_record_image_url: "text",
    kitta_no: "character varying",
    palika: "character varying",
    current_ward_no: "integer",
    area: "character varying",
    use_for: "character varying",
    road_type: "character varying",
    owner_name: "character varying",
    is_self_used: "boolean",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_lightingsource: {
    id: "integer",
    main_source: "character varying",
    other_source: "character varying",
    has_meter: "boolean",
    reason_not_using_electricity: "text",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_loan: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    loan_for: "character varying",
    source_of_loan: "character varying",
    loan_amount: "real",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_saving: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    saving_field: "character varying",
    saving_amount: "real",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_school: {
    id: "integer",
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    school_type: "character varying",
    ways_to_reach_school: "character varying",
    time_to_reach_school: "real",
    ward_no: "integer",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_toilet: {
    id: "integer",
    toilet_type: "character varying",
    house: "Relation[() => digital_profile_house_1.digital_profile_house]",
  },
  digital_profile_house: {
    created_at: "timestamp without time zone",
    updated_at: "timestamp without time zone",
    latitude: "real",
    longitude: "real",
    ward_no: "integer",
    google_plus_code: "character varying",
    district: "character varying",
    province: "character varying",
    owner_eng: "character varying",
    owner_nepali: "character varying",
    total_family_members: "integer",
    family_death_within_1_year: "boolean",
    digital_profile_agriculturecashcrops:
      "Relation[() => digital_profile_agriculturecashcrop_1.digital_profile_agriculturecashcrop]",
    digital_profile_agricultureflowers:
      "Relation[() => digital_profile_agricultureflowers_1.digital_profile_agricultureflowers]",
    digital_profile_agriculturefoodcrops:
      "Relation[() => digital_profile_agriculturefoodcrop_1.digital_profile_agriculturefoodcrop]",
    digital_profile_agriculturefruits:
      "Relation[() => digital_profile_agriculturefruits_1.digital_profile_agriculturefruits]",
    digital_profile_agricultureoilseeds:
      "Relation[() => digital_profile_agricultureoilseeds_1.digital_profile_agricultureoilseeds]",
    digital_profile_agriculturepulses:
      "Relation[() => digital_profile_agriculturepulses_1.digital_profile_agriculturepulses]",
    digital_profile_agriculturevegetables:
      "Relation[() => digital_profile_agriculturevegetable_1.digital_profile_agriculturevegetable]",
    digital_profile_buildingdetails:
      "Relation[() => digital_profile_buildingdetail_1.digital_profile_buildingdetail]",
    digital_profile_cookingfuels:
      "Relation[() => digital_profile_cookingfuel_1.digital_profile_cookingfuel]",
    digital_profile_drinkingwatersurveys:
      "Relation[() => digital_profile_drinkingwatersurvey_1.digital_profile_drinkingwatersurvey]",
    digital_profile_educations:
      "Relation[() => digital_profile_education_1.digital_profile_education]",
    digital_profile_expenses:
      "Relation[() => digital_profile_expense_1.digital_profile_expense]",
    digital_profile_familydeaths:
      "Relation[() => digital_profile_familydeath_1.digital_profile_familydeath]",
    digital_profile_familymembers:
      "Relation[() => digital_profile_familymember_1.digital_profile_familymember]",
    digital_profile_healthtreatments:
      "Relation[() => digital_profile_healthtreatment_1.digital_profile_healthtreatment]",
    digital_profile_lands:
      "Relation[() => digital_profile_land_1.digital_profile_land]",
    digital_profile_lightingsources:
      "Relation[() => digital_profile_lightingsource_1.digital_profile_lightingsource]",
    digital_profile_loans:
      "Relation[() => digital_profile_loan_1.digital_profile_loan]",
    digital_profile_savings:
      "Relation[() => digital_profile_saving_1.digital_profile_saving]",
    digital_profile_schools:
      "Relation[() => digital_profile_school_1.digital_profile_school]",
    digital_profile_toilets:
      "Relation[() => digital_profile_toilet_1.digital_profile_toilet]",
  },
  hospital: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    category: "character varying",
    use: "character varying",
    name: "character varying",
    ward: "numeric",
  },
  school: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    category: "character varying",
    use: "character varying",
    name: "character varying",
    ward: "numeric",
  },
  temple: {
    ogc_fid: "integer",
    wkb_geometry: "geometry",
    category: "character varying",
    use: "character varying",
    name: "character varying",
    ward: "numeric",
  },
  consultation_record: {
    firstName: "varchar",
    lastName: "varchar",
    email: "varchar",
    phoneNumber: "varchar",
    organizationName: "varchar",
    queries: "text",
    preferredTime: "timestamp",
    status: "enum",
    createdAt: "timestamp",
    updatedAt: "timestamp",
  },
  ghar_bato_sifarish: {
    ownerEng: "varchar",
    ownerNepali: "varchar",
    municipality: "varchar",
    tole: "varchar",
    uuid: "varchar",
    isValid: "boolean",
    access_road_is_present: "boolean",
    access_road_width: "numeric",
    access_road_pavement_type: "enum",
    acess_road_name: "varchar",
    secondary_road_is_present: "boolean",
    secondary_road_width: "numeric",
    secondary_road_pavement_type: "enum",
    secondary_road_name: "varchar",
    main_road_is_present: "boolean",
    main_road_width: "numeric",
    main_road_pavement_type: "enum",
    main_road_name: "varchar",
    cadastral: "Relation[() => cadastral_1.cadastral]",
  },
  spatial_ref_sys: {
    srid: "integer",
    auth_name: "character varying",
    auth_srid: "integer",
    srtext: "character varying",
    proj4text: "character varying",
  },
};
